# An example of ClusterConfig object with access to CSI drivers:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tensorpack-mask-rcnn-p3
  region: us-east-1


vpc:
  id: "vpc-f6570b8d"  # (optional, must match VPC ID used for each subnet below)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      us-east-1b:
        id: "subnet-58b35b04"

      us-east-1c:
        id: "subnet-b440b9d3"

      us-east-1f:
        id: "subnet-21ac2f2e"

nodeGroups:
  - name: ng-p3-1f
    instanceType: p3.16xlarge
    availabilityZones: ["us-east-1f"]
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        imageBuilder: true
        ebs: true
        fsx: true
        efs: true
    ssh:
      allow: true
      publicKeyName: 'maskrcnn'
